### ISSUE TITLE
Access the A1111 serverless instance while in_progress

### ISSUE THREAD

**Issue by EternalC0der** [ashleykleynhans/runpod-worker-a1111#15]
Hello,

I'm currently exploring the feasibility of tracking the progress of image generation via the API. Specifically, I'm interested in real-time updates on the image being generated, not just the operational status of the runpod serverless instance. Previously, we utilized an API endpoint in A1111 WebUI for this purpose. However, since our API requests are now routed through the runpod serverless instance, it's unclear how to maintain this functionality.

Is there a method to access the image generation progress directly from A1111 WebUI in a way that avoids the issue where a request to the get_progress API is either queued until image generation is complete or, in some cases, triggers the launch of a new serverless instance to obtain progress, rendering the information irrelevant for the current task? This feature is critical for us as we aim to provide live generation updates on our frontend.

Any guidance or suggestions you could provide would be greatly appreciated.

Thank you for your support.

**Comment by ashleykleynhans** [comment]
Don't think this is possible, since it this worker relies on A1111's APIs.
