### ISSUE TITLE
S3 image uploads

### ISSUE THREAD

**Issue by niccolofanton** [ashleykleynhans/runpod-worker-a1111#17]
Hi, first of all, thanks for the repo, it's super helpful

I need to save the images generated from the model to S3 to avoid heavy network usage in my infrastructure. In the [runpod documentation](https://docs.runpod.io/serverless/workers/development/environment-variables#python-code-for-s3-uploads) there is a helper that handles this feature.

Can this feature be used out of the box with this template? If not, how can I implement it? 

Thanks

**Comment by ashleykleynhans** [comment]
All of the RunPod serverless utility functions are available to all workers via the RunPod SDK, simply add the S3 config to your payload.

**Comment by ashleykleynhans** [comment]
Actually this doesn't support it, only base64 is supported, I am not supporting S3, base64 is good enough for most use cases, fork the repo if you need S3 support and add it.
