### ISSUE TITLE
NOOB question... How do i run inference or access web-ui using this setup?

### ISSUE THREAD

**Issue by adam-clarey** [ashleykleynhans/runpod-worker-a1111#18]
I've run through the instructions in the README, the pod is running which is great. I can connect to Jupyter, but there seems to be no instructions that I can find anywhere on how to actual run inference requests on a pod, or to access the webui.

I can see only port 8888 is open be default, no other ports, so how are they accessed on a 'Pod'? I can see Serverless provides an endpoint url for inference which makes it obvious there (although not clear how webui would run from a serverless pod).

**Comment by ashleykleynhans** [comment]
Read container logs and wait for syncing to complete.

**Comment by ashleykleynhans** [comment]
This is not for a pod, there is no Jupyter, its designed for serverless, please read the RunPod blogs etc and learn how to use serverless, I don't have time and neither is it my job to explain to people how to use RunPod serverless.  Don't use this if you don't know how to use RunPod Serverless.
