### ISSUE TITLE
Img2img + ControlNet works on the WebUI interface, but does not work via an API call

### ISSUE THREAD

**Issue by the-one-and-only-zephiron** [ashleykleynhans/runpod-worker-a1111#22]
Hey, ashley, thanks in advance for any help provided.
I'm trying to run a serverless API to an automatic1111's WebUI interface via your guide,  and it's been super helpful! model loading and image generation are a breeze, but controlnet does not seem to work when I make an API call, here is an example:

**Base Image:** 
![baixados (2)](https://github.com/ashleykleynhans/runpod-worker-a1111/assets/87841019/ca609421-f344-45ee-ab29-96faa0f4db06)

**WebUI interface result:**
![00008-4073374742 (1)](https://github.com/ashleykleynhans/runpod-worker-a1111/assets/87841019/242cd868-4f9e-4f8a-ac72-f75ef51fbfe5)

**WebUI prompt:**

> photorealistic, a photo of a modern dining room, moody lighting, color grading, Unreal Engine 5, foreground, middleground and background well defined
Negative prompt: bad quality, lowres, unfaithful geometry, jpeg artifacts, black outlines, low quality, bad geometry, bad text
Steps: 30, Sampler: DPM++ 2M, Schedule type: Karras, CFG scale: 7, Seed: 4073374742, Size: 867x1080, Model hash: 0928b30687, Model: realisticVisionV60B1_v51HyperVAE, Denoising strength: 0.6, ControlNet 0: "Module: canny, Model: control_v11p_sd15_canny, Weight: 1.0, Resize Mode: Crop and Resize, Processor Res: 512, Threshold A: 75.0, Threshold B: 75.0, Guidance Start: 0.0, Guidance End: 1.0, Pixel Perfect: True, Control Mode: ControlNet is more important", Version: v1.9.3

**Postman request result:** 
![baixados (3)](https://github.com/ashleykleynhans/runpod-worker-a1111/assets/87841019/6d43c117-ff21-42b0-889f-0a8c425611a3)

**Postman request body:**
`{
    "input": {
        "api": {
            "method": "POST",
            "endpoint": "/sdapi/v1/img2img"
        },
        "payload": {
            "init_images": [
                "base64 encoded image"
            ],
            "override_settings": {
                "sd_model_checkpoint": "realisticVisionV60B1_v51HyperVAE"
            },
            "override_settings_restore_afterwards": true,
            "prompt": "photorealistic, a photo of a modern dining room, moody lighting, color grading, Unreal Engine 5, foreground, middleground and background well defined",
            "negative_prompt":"bad quality, lowres, unfaithful geometry, jpeg artifacts, black outlines, low quality, bad geometry, bad text",
            "scheduler": "karras",
            "sampler_name": "DPM++ 2M",
            "sampler_index": "DPM++ 2M",
            "steps": 30,
            "cfg_scale": 7,
            "denoising_strength": 0.60,
            "width":867,
            "height":1080,
            "restore_faces": false,
            "alwayson_scripts": {
             "controlnet": {
                 "args": [
                   {
                     "module": "canny",
                     "model": "control_v11p_sd15_canny",
                     "weight": 1,
                     "resize_mode": "Crop and Resize",
                     "lowvram": false,
                     "processor_res": 512,
                    "threshold_a": 75,
                     "threshold_b": 75,
                     "guidance_start": 0,
                     "guidance_end": 1,
                     "control_mode": "ControlNet is more important",
                     "pixel_perfect": true
            }
          ]
        }
      }
        }
    }
}`

Also, this is my first github issue opened, so sorry in advance for any formatting errors.

**Comment by the-one-and-only-zephiron** [comment]
Hey guys, I just solved it! For anyone having the same problem as me, all I did was replace "controlnet" with "ControlNet" in the json and using the argument "enabled": true in the controlnet arguments!

**Comment by the-one-and-only-zephiron** [comment]
Hey guys, I just solved it! For anyone having the same problem as me, all I did was replace "controlnet" with "ControlNet" in the json and using the argument "enabled": true in the controlnet arguments!

I don't know if it was the "ControlNet" or the "enabled": true, but the issue is solved.

**Comment by lucas-martinic** [comment]
Hey @the-one-and-only-zephiron, quick question, where did you place the controlnet models? I'm having the issue that my A1111 wants to load them from /runpod-volume/stable-diffusion-webui/extensions/sd-webui-controlnet/models/ but also doesn't allow me to add models there.
