### ISSUE TITLE
Faster inferences

### ISSUE THREAD

**Issue by Swarzox** [ashleykleynhans/runpod-worker-a1111#23]
First of all, thank you for the excellent work on this repository. Everything works perfectly.

I would like to know if there are any ways to optimize the performance to achieve the fastest possible inference times, if this hasn't been done already. I'm trying to run SDXL Lightning with 4 steps and aim to minimize the generation time as much as possible to optimize my costs. Do you have any tips or suggestions?

Thank you in advance!

**Comment by ashleykleynhans** [comment]
I can't help with this, its up to A1111, log an issue on the A1111 Github repo.
