### ISSUE TITLE
img2img fails / Inpainting not possible: "Unexpected input. mask is not a valid input option"

### ISSUE THREAD

**Issue by dubtor** [ashleykleynhans/runpod-worker-a1111#24]
Observed:
When trying to use the "img2img" endpoint, it is not possible to pass in a "mask" image. 

This, in turn, makes it impossible to use any form of inpainting.

This problem seems to occur because in schemas/Img2img.py, the parameter "mask" is commented out:
<img width="641" alt="image" src="https://github.com/ashleykleynhans/runpod-worker-a1111/assets/16031950/48e5562a-02a2-48bf-8dd1-9793d6cdd285">

Expected:
It should be possible to provide a mask for the img2img checkpoint

Thank you ❤️

**Comment by ashleykleynhans** [comment]
This is just s serverless worker for A1111, log A1111 issues on A1111 Github repo:

https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by dubtor** [comment]
Dear @ashleykleynhans thanks for getting back!

Just to confirm I understand correctly:

In my case, I am making a serverless worker request to A1111 through your template. The request goes through correctly and validates all stable diffusion-specific inputs I am sending to the /img2img/ endpoint. This request eventually gets rejected for invalid payload inputs, due to me passing in a "mask" parameter, which is a standard paramter. This rejection seems to occur on your end of the code because this one particular parameter "mask" has been commented out of the list of valid parameters in IMG2IMG_SCHEMA (schemas/img2img.py)

Are you saying that this parameter is also commented out in stable diffusion webUI or that those schemas in your code are simply copied over? Thank you!

**Comment by ashleykleynhans** [comment]
Not sure, I must have commented out mask for breaking things.

**Comment by ashleykleynhans** [comment]
You can try fork it and uncomment it but I don't have time.

**Comment by dubtor** [comment]
I'll give it a go, thank you very much 🙏
