### ISSUE TITLE
Option to not use network storage?

### ISSUE THREAD

**Issue by arjunmehta** [ashleykleynhans/runpod-worker-a1111#25]
I understand all instructions guide towards using a network volume to store A1111, models etc. However, this comes with slower cold start times, and I've even had some network attachments fail, which has caused some odd billing issues for us. 

Do you think it would be possible to modify this config to use the container's local volume storage and not rely on a network volume? Or do you think that would be a separate project entirely?

I'm assuming to do that would mean modifying the dockerfile/template config to download/install A1111 to a template's **volume disk** on initialization.

I'd be happy to contribute or even just fork, but would love to hear your thoughts.

**Comment by ashleykleynhans** [comment]
There is no volume disk in serverless.  Only container disk and network volume.  You have to bake the models into the docker image if you don't use a network volumd and that will result in a massive docker image.  I am not going to change it.

**Comment by arjunmehta** [comment]
Ah apologies, my mistake. I saw the option for Volume disk in the template creation step but realize now that is only for Pod templates and not Serverless.
