### ISSUE TITLE
Worker gets stuck in "Service not ready yet. Retrying..." state for long periods of time

### ISSUE THREAD

**Issue by arjunmehta** [ashleykleynhans/runpod-worker-a1111#26]
It seems often that using this container and configuration, workers are getting stuck in a state where they are not getting "ready".

<img width="1286" alt="Screenshot 2024-07-12 at 16 46 01" src="https://github.com/user-attachments/assets/71825469-a1fb-4e73-b004-70c0a7ca8fc8">
<img width="449" alt="Screenshot 2024-07-12 at 22 43 13" src="https://github.com/user-attachments/assets/9e427799-4e97-41bc-bc5c-56f98c2deb8d">

This is likely causing a large depletion of balance on our accounts, as there isn't a timeout for anything other than execution time.

Any idea what could be done to solve this problem?

Logs are overwritten by every worker execution but I have noticed that in some cases the logs indicate that cache becomes corrupted, but it's not clear that prevents A1111 from loading.

**Comment by ashleykleynhans** [comment]
This works fine for me, try a different region, probably something wrong with your network storage if its loading too slowly and files are becoming corrupted.  Its also a RunPod bug where multiple workers are spawned for the same request, nothing I can do about this, tell RunPod to fix it.
