### ISSUE TITLE
Template disappeared in Runpod

### ISSUE THREAD

**Issue by RicMlg** [ashleykleynhans/runpod-worker-a1111#29]
Hi, I have been working with your templates in Runpod for weeks, but now I see that they have disappeared. Is it temporary or permanent? Because I have not read any statement. Thank you very much.

**Comment by ashleykleynhans** [comment]
You have logged this in the wrong repo, this is for serverless and still available, only my pod templates were removed from the RunPod platform.  Serverless ones continue to function as normal.
