### ISSUE TITLE
Can you add a webshell api?

### ISSUE THREAD

**Issue by kecikeci** [ashleykleynhans/runpod-worker-a1111#3]
I have an idea,add a webshell api,Pass in the shell statement,Then return the result via Webhook.

This enables online downloading of models

**Comment by ashleykleynhans** [comment]
This is not a good idea. You are billed per second that your RunPod worker runs so I have designed this worker to not download models at run time intentionally and will never add the ability to download models at run time.  You can either build the model into your docker image or store it on a network volume.  You don't need any webshell, you can add models to your network drive by attaching it to a pod, and RunPod serverless already supports webhooks.

**Comment by kecikeci** [comment]
But it is very troublesome to operate the files in the network volume or put the model in the docker, and I think it costs the same amount of money. Instead, it is very convenient to use the webshell to download, the download speed is fast, and it does not take a lot of time

**Comment by ashleykleynhans** [comment]
@kecikeci feel free to fork it and add that feature, I am not going to add it.

**Comment by kecikeci** [comment]
> @kecikeci feel free to fork it and add that feature, I am not going to add it.

My python skills are not good, I am a java programmer, can you please open a branch and add
