### ISSUE TITLE
How to make the return request of webhook only be requested once

### ISSUE THREAD

**Issue by kecikeci** [ashleykleynhans/runpod-worker-a1111#4]
How to make the return request of webhook only be requested once?

Because the logic of my webhook processing is more complex and time-consuming, then I found that the webhook will call back every 12 seconds. How to make webhook only called once?

**Comment by ashleykleynhans** [comment]
Please ask RunPod about this, I have no control over how their webhooks work.

**Comment by kecikeci** [comment]
> Please ask RunPod about this, I have no control over how their webhooks work.

OK, thanks
