### ISSUE TITLE
Roop support

### ISSUE THREAD

**Issue by selivandex** [ashleykleynhans/runpod-worker-a1111#5]
Hey! First of all thanks for this awesome repo!

Could you please add roop support here?

**Comment by ashleykleynhans** [comment]
There are no plans to install roop, but you can either install it using similar extensions to the ControlNet extensions.  You can install as many extensions as you want that way, or else use my inswapper RunPod serverless worker which can do face swaps on any images, not just those generated by Stable Diffusion.  I am using the A1111 worker for generating images using Stable Diffusion and the inwapper worker for face swaps.

https://github.com/ashleykleynhans/runpod-worker-inswapper

**Comment by ashleykleynhans** [comment]
Feel free to read the [FAQ](https://github.com/ashleykleynhans/runpod-worker-a1111/blob/main/docs/faq.md) for installing the roop extension.

**Comment by ashleykleynhans** [comment]
ReActor extension has been added instead of roop.
